name: Run Tests Pipeline

on:
  pull_request:
    branches: ["master"]

permissions:
  contents: write
  pull-requests: write

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run unit tests
        run: mvn -B clean test


  api-tests:
    name: API tests (RestAssured)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Run API tests
        run: mvn -B -Papi verify


  web-tests:
    name: Web tests (Selenium/Cucumber)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Web tests
        env:
          CI: true
        run: mvn -B -Pweb verify


  auto-merge:
    name: Auto Merge PR
    needs: [unit-tests, api-tests, web-tests]
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - name: Merge pull request
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
